<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27468" started-at="2016-12-09T09:27:24Z" finished-at="2016-12-09T09:27:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27468" started-at="2016-12-09T09:27:24Z" finished-at="2016-12-09T09:27:52Z">
      <class name="scripts.ValidLoginLogout">
        <test-method status="PASS" signature="precondition()[pri:0, instance:scripts.ValidLoginLogout@4f933fd1]" name="precondition" is-config="true" duration-ms="23930" started-at="2016-12-09T14:57:24Z" finished-at="2016-12-09T14:57:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testValidLoginLogout()[pri:0, instance:scripts.ValidLoginLogout@4f933fd1]" name="testValidLoginLogout" duration-ms="3415" started-at="2016-12-09T14:57:48Z" finished-at="2016-12-09T14:57:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [actiTIME - Login]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at pom.BasePage.verifyTitle(BasePage.java:19)
	at scripts.ValidLoginLogout.testValidLoginLogout(ValidLoginLogout.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLoginLogout -->
        <test-method status="PASS" signature="postcondition()[pri:0, instance:scripts.ValidLoginLogout@4f933fd1]" name="postcondition" is-config="true" duration-ms="22" started-at="2016-12-09T14:57:52Z" finished-at="2016-12-09T14:57:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- scripts.ValidLoginLogout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
